### ISSUE TITLE
为什么连接不了kimi

### ISSUE THREAD

**Issue by w3yyb** [webman-php/openai#4]
报：{"error":{"code":"exception","message":"connect api.moonshot.cn:443 timeout after 30 seconds","detail":"Exception: connect api.moonshot.cn:443 timeout after 30 seconds in \/var\/www\/html\/aichat_webman\/vendor\/workerman\/http-client\/src\/Request.php:465\nStack trace:\n#0 [internal function]: Workerman\\Http\\Request->onError()\n#1 \/var\/www\/html\/aichat_webman\/vendor\/workerman\/http-client\/src\/ConnectionPool.php(175): call_user_func()\n#2 \/var\/www\/html\/aichat_webman\/vendor\/workerman\/workerman\/Events\/Select.php(238): Workerman\\Http\\ConnectionPool->closeTimeoutConnection()\n#3 \/var\/www\/html\/aichat_webman\/vendor\/workerman\/workerman\/Events\/Select.php(299): Workerman\\Events\\Select->tick()\n#4 \/var\/www\/html\/aichat_webman\/vendor\/workerman\/workerman\/Worker.php(1719): Workerman\\Events\\Select->loop()\n#5 \/var\/www\/html\/aichat_webman\/vendor\/workerman\/workerman\/Worker.php(1510): Workerman\\Worker::forkOneWorkerForLinux()\n#6 \/var\/www\/html\/aichat_webman\/vendor\/workerman\/workerman\/Worker.php(1484): Workerman\\Worker::forkWorkersForLinux()\n#7 \/var\/www\/html\/aichat_webman\/vendor\/workerman\/workerman\/Worker.php(561): Workerman\\Worker::forkWorkers()\n#8 \/var\/www\/html\/aichat_webman\/vendor\/workerman\/webman-framework\/src\/support\/App.php(143): Workerman\\Worker::runAll()\n#9 \/var\/www\/html\/aichat_webman\/start.php(4): support\\App::run()\n#10 {main}"}}

**Comment by w3yyb** [comment]
连接其它的没有 问题，目前只有kimi连不了

**Comment by walkor** [comment]
服务器在哪个城市？
在服务器上运行命令 `curl https://api.moonshot.cn` 看看是否能连上

**Comment by w3yyb** [comment]
在我自己电脑上，我用curl是可以连接的 

curl_setopt_array($curl, array(
  CURLOPT_URL => 'https://api.moonshot.cn/v1/chat/completions',
  CURLOPT_RETURNTRANSFER => false,//// 对SSE设置为false
  CURLOPT_ENCODING => '',
  CURLOPT_MAXREDIRS => 10,
  CURLOPT_TIMEOUT => 0,
  CURLOPT_FOLLOWLOCATION => true,
  CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
  CURLOPT_CUSTOMREQUEST => 'POST',
  CURLOPT_POSTFIELDS =>'{
  "messages": '.$postMsg.',
  "model": "moonshot-v1-auto",
  "response_format": {
    "type": "text"
  },
  "stop": null,
  "stream": true,
  "temperature": '.$theusetemperature.'
}',
  CURLOPT_HTTPHEADER => array(
    'Content-Type: application/json',
    'Accept: application/json',
    'Authorization: Bearer sk-xxxxxxxxxxx',
    "Accept: text/event-stream",
    "Cache-Control: no-cache",
    "Connection: keep-alive"
  ),
));


// 定义数据接收的回调
curl_setopt($curl, CURLOPT_WRITEFUNCTION, function ($curl, $data) {
  echo $data; // 直接输出接收到的流数据
  flush();    // 确保数据实时输出到浏览器
  return strlen($data);
});

$response = curl_exec($curl);

curl_close($curl);

**Comment by walkor** [comment]
看报错是连接30秒超时，其它看不出什么问题。

**Comment by w3yyb** [comment]
可以了，我把网络从云南联通换为移动就可以了
